import * as React from "react";

import { ButtonPreviewBlocks } from "./ButtonPreviewBlocks";
import { SpinnerPreviewBlocks } from "./SpinnerPreviewBlocks";
import { MessageBoxPreviewBlocks } from "./MessageBoxPreviewBlocks";
import { SwitchPreviewBlocks } from "./SwitchPreviewBlocks";
import { RadioPreviewBlocks } from "./RadioPreviewBlocks";
import { DropdownPreviewBlocks } from "./DropdownPreviewBlocks";

export type MappingType = {
  [category: string]: {
    [unit: string]: {
      [section: string]: () => React.JSX.Element;
    };
  };
};

export const mapping: MappingType = {
  presets: {
    "social-media-card": { usage: ButtonPreviewBlocks.Usage },
    "music-player": { usage: ButtonPreviewBlocks.Usage },
    "statistics-cards": { usage: ButtonPreviewBlocks.Usage },
    "settings-panel": { usage: ButtonPreviewBlocks.Usage },
    "action-buttons": { usage: ButtonPreviewBlocks.Usage },
    "status-indicators": { usage: ButtonPreviewBlocks.Usage },
    "navigation-pills": { usage: ButtonPreviewBlocks.Usage },
    "quick-actions": { usage: ButtonPreviewBlocks.Usage },
    "weather-widget": { usage: ButtonPreviewBlocks.Usage },
    "notification-cards": { usage: ButtonPreviewBlocks.Usage },
    "todo-list": { usage: ButtonPreviewBlocks.Usage },
    "chat-messages": { usage: ButtonPreviewBlocks.Usage },
    "activity-feed": { usage: ButtonPreviewBlocks.Usage },
    "shopping-cart": { usage: ButtonPreviewBlocks.Usage },
    "file-upload-area": { usage: ButtonPreviewBlocks.Usage },
    "progress-tracker": { usage: ButtonPreviewBlocks.Usage },
    "media-controls": { usage: ButtonPreviewBlocks.Usage },
    "pricing-card": { usage: ButtonPreviewBlocks.Usage },
    "calendar-widget": { usage: ButtonPreviewBlocks.Usage },
    "device-status": { usage: ButtonPreviewBlocks.Usage },
    "analytics-dashboard": { usage: ButtonPreviewBlocks.Usage },
    "contact-card": { usage: ButtonPreviewBlocks.Usage },
    "file-manager": { usage: ButtonPreviewBlocks.Usage },
    "quick-stats": { usage: ButtonPreviewBlocks.Usage },
    "mini-menu": { usage: ButtonPreviewBlocks.Usage },
    "notification-badges": { usage: ButtonPreviewBlocks.Usage },
    "profile-badge": { usage: ButtonPreviewBlocks.Usage },
    "time-&-location-widget": { usage: ButtonPreviewBlocks.Usage },
    "energy-meter": { usage: ButtonPreviewBlocks.Usage },
    "cryptocurrency-widget": { usage: ButtonPreviewBlocks.Usage },
    "gaming-controller-widget": { usage: ButtonPreviewBlocks.Usage },
    "streak-counter": { usage: ButtonPreviewBlocks.Usage },
    "layer-stack-widget": { usage: ButtonPreviewBlocks.Usage },
    "inspiration-widget": { usage: ButtonPreviewBlocks.Usage },
    "nature-widget": { usage: ButtonPreviewBlocks.Usage },
    "reading-progress": { usage: ButtonPreviewBlocks.Usage },
    "idea-bulb-widget": { usage: ButtonPreviewBlocks.Usage },
    "rocket-launch-widget": { usage: ButtonPreviewBlocks.Usage },
    "tool-widget": { usage: ButtonPreviewBlocks.Usage },
    "color-palette-widget": { usage: ButtonPreviewBlocks.Usage },
    "system-status": { usage: ButtonPreviewBlocks.Usage },
    "pomodoro-timer": { usage: ButtonPreviewBlocks.Usage },
    "database-widget": { usage: ButtonPreviewBlocks.Usage },
    "network-status": { usage: ButtonPreviewBlocks.Usage },
    "code-stats": { usage: ButtonPreviewBlocks.Usage },
    "mouse-tracker": { usage: ButtonPreviewBlocks.Usage },
    "design-system": { usage: ButtonPreviewBlocks.Usage },
    "ai-assistant": { usage: ButtonPreviewBlocks.Usage },
    "office-building-widget": { usage: ButtonPreviewBlocks.Usage },
    "team-collaboration-widget": { usage: ButtonPreviewBlocks.Usage },
    "health-monitor": { usage: ButtonPreviewBlocks.Usage },
    "email-dashboard": { usage: ButtonPreviewBlocks.Usage },
    "document-scanner": { usage: ButtonPreviewBlocks.Usage },
    "social-engagement": { usage: ButtonPreviewBlocks.Usage },
    "video-call-widget": { usage: ButtonPreviewBlocks.Usage },
    "task-manager": { usage: ButtonPreviewBlocks.Usage },
    "fitness-tracker": { usage: ButtonPreviewBlocks.Usage },
    "cloud-storage": { usage: ButtonPreviewBlocks.Usage },
    "language-learning": { usage: ButtonPreviewBlocks.Usage },
    "stock-market": { usage: ButtonPreviewBlocks.Usage },
    "recipe-finder": { usage: ButtonPreviewBlocks.Usage },
    "travel-planner": { usage: ButtonPreviewBlocks.Usage },
    "budget-tracker": { usage: ButtonPreviewBlocks.Usage },
    "password-manager": { usage: ButtonPreviewBlocks.Usage },
    "photo-editor": { usage: ButtonPreviewBlocks.Usage },
    "music-production": { usage: ButtonPreviewBlocks.Usage },
    "shopping-list": { usage: ButtonPreviewBlocks.Usage },
    "habit-tracker": { usage: ButtonPreviewBlocks.Usage },
    "code-editor": { usage: ButtonPreviewBlocks.Usage },
  },
  components: {
    button: {
      usage: ButtonPreviewBlocks.Usage,
      disabled: ButtonPreviewBlocks.Disabled,
      loading: ButtonPreviewBlocks.Loading,
      sizes: ButtonPreviewBlocks.Sizes,
      radius: ButtonPreviewBlocks.Radius,
      variants: ButtonPreviewBlocks.Variants,
      appearance: ButtonPreviewBlocks.Appearance,
      "with-icon": ButtonPreviewBlocks.WithIcon,
      "button-group": ButtonPreviewBlocks.ButtonGroup,
      "button-group-disabled": ButtonPreviewBlocks.ButtonGroupDisabled,
      "button-group-alignment": ButtonPreviewBlocks.ButtonGroupAlignment,
      "button-group-radius": ButtonPreviewBlocks.ButtonGroupRadius,
      "button-group-size": ButtonPreviewBlocks.ButtonGroupSize,
      "button-group-variant": ButtonPreviewBlocks.ButtonGroupVariant,
    },
    spinner: {
      usage: SpinnerPreviewBlocks.Usage,
      sizes: SpinnerPreviewBlocks.Sizes,
      types: SpinnerPreviewBlocks.Types,
      variants: SpinnerPreviewBlocks.Variants,
    },
    "message-box": {
      usage: MessageBoxPreviewBlocks.Usage,
      types: MessageBoxPreviewBlocks.Types,
      variants: MessageBoxPreviewBlocks.Variants,
      radius: MessageBoxPreviewBlocks.Radius,
      "without-icon": MessageBoxPreviewBlocks.WithoutIcon,
    },
    switch: {
      checked: SwitchPreviewBlocks.Checked,
      usage: SwitchPreviewBlocks.Usage,
      variants: SwitchPreviewBlocks.Variants,
      labeled: SwitchPreviewBlocks.Labeled,
      "align-label": SwitchPreviewBlocks.AlignLabel,
      disabled: SwitchPreviewBlocks.Disabled,
      sizes: SwitchPreviewBlocks.Sizes,
      controlled: SwitchPreviewBlocks.Controlled,
      "track-icon": SwitchPreviewBlocks.TrackIcon,
      "thumb-icon": SwitchPreviewBlocks.ThumbIcon,
    },
    radio: {
      usage: RadioPreviewBlocks.Usage,
      disabled: RadioPreviewBlocks.Disabled,
      sizes: RadioPreviewBlocks.Sizes,
      variants: RadioPreviewBlocks.Variants,
      appearance: RadioPreviewBlocks.Appearance,
      "highlight-label": RadioPreviewBlocks.HighlightLabel,
      "radio-group-align": RadioPreviewBlocks.RadioGroupAlign,
      "align-label": RadioPreviewBlocks.AlignLabel,
      controlled: RadioPreviewBlocks.Controlled,
    },
    dropdown: {
      usage: DropdownPreviewBlocks.Usage,
      disabled: DropdownPreviewBlocks.Disabled,
      appearance: DropdownPreviewBlocks.Appearance,
    },
  },
};
