# name-template: 'v$RESOLVED_VERSION'
# tag-template: 'v$RESOLVED_VERSION'
# categories:
#   - title: 'Breaking Changes'
#     labels: ['breaking']
#   - title: 'Features'
#     labels: ['feature', 'enhancement']
#   - title: 'Fixes'
#     labels: ['fix', 'bug']
#   - title: 'Documentation'
#     labels: ['documentation']
#   - title: 'Chores'
#     labels: ['chore', 'maintenance']
# change-template: '- $TITLE (#$NUMBER) — @$AUTHOR'
# template: |
#   ## Changes
#   $CHANGES
