export const components = {
  "get-started": {
    overview: ["ComponentName"],
  },
  presets: {
    "social-media-card": ["SocialMediaCard"],
    "music-player": ["MusicPlayer"],
    "statistics-cards": ["StatisticsCards"],
    "settings-panel": ["SettingsPanel"],
    "action-buttons": ["ActionButtons"],
    "status-indicators": ["StatusIndicators"],
    "navigation-pills": ["NavigationPills"],
    "quick-actions": ["QuickActions"],
    "weather-widget": ["WeatherWidget"],
    "notification-cards": ["NotificationCards"],
    "todo-list": ["TodoList"],
    "chat-messages": ["ChatMessages"],
    "activity-feed": ["ActivityFeed"],
    "shopping-cart": ["ShoppingCart"],
    "file-upload-area": ["FileUploadArea"],
    "progress-tracker": ["ProgressTracker"],
    "media-controls": ["MediaControls"],
    "pricing-card": ["PricingCard"],
    "calendar-widget": ["CalendarWidget"],
    "device-status": ["DeviceStatus"],
    "analytics-dashboard": ["AnalyticsDashboard"],
    "contact-card": ["ContactCard"],
    "file-manager": ["FileManager"],
    "quick-stats": ["QuickStats"],
    "mini-menu": ["MiniMenu"],
    "notification-badges": ["NotificationBadges"],
    "profile-badge": ["ProfileBadge"],
    "time-&-location-widget": ["TimeLocationWidget"],
    "energy-meter": ["EnergyMeter"],
    "cryptocurrency-widget": ["CryptocurrencyWidget"],
    "gaming-controller-widget": ["GamingControllerWidget"],
    "streak-counter": ["StreakCounter"],
    "layer-stack-widget": ["LayerStackWidget"],
    "inspiration-widget": ["InspirationWidget"],
    "nature-widget": ["NatureWidget"],
    "reading-progress": ["ReadingProgress"],
    "idea-bulb-widget": ["IdeaBulbWidget"],
    "rocket-launch-widget": ["RocketLaunchWidget"],
    "tool-widget": ["ToolWidget"],
    "color-palette-widget": ["ColorPaletteWidget"],
    "system-status": ["SystemStatus"],
    "pomodoro-timer": ["PomodoroTimer"],
    "database-widget": ["DatabaseWidget"],
    "network-status": ["NetworkStatus"],
    "code-stats": ["CodeStats"],
    "mouse-tracker": ["MouseTracker"],
    "design-system": ["DesignSystem"],
    "ai-assistant": ["AIAssistant"],
    "office-building-widget": ["OfficeBuildingWidget"],
    "team-collaboration-widget": ["TeamCollaborationWidget"],
    "health-monitor": ["HealthMonitor"],
    "email-dashboard": ["EmailDashboard"],
    "document-scanner": ["DocumentScanner"],
    "social-engagement": ["SocialEngagement"],
    "video-call-widget": ["VideoCallWidget"],
    "task-manager": ["TaskManager"],
    "fitness-tracker": ["FitnessTracker"],
    "cloud-storage": ["CloudStorage"],
    "language-learning": ["LanguageLearning"],
    "stock-market": ["StockMarket"],
    "recipe-finder": ["RecipeFinder"],
    "travel-planner": ["TravelPlanner"],
    "budget-tracker": ["BudgetTracker"],
    "password-manager": ["PasswordManager"],
    "photo-editor": ["PhotoEditor"],
    "music-production": ["MusicProduction"],
    "shopping-list": ["ShoppingList"],
    "habit-tracker": ["HabitTracker"],
    "code-editor": ["CodeEditor"],
  },
  components: {
    anchor: ["Anchor"],
    button: ["Button", "ButtonGroup"],
    label: ["Label"],
    card: ["Card"],
    dropdown: ["Dropdown", "DropdownOption"],
    "message-box": ["MessageBox"],
    spinner: ["Spinner"],
    switch: ["Switch"],
    radio: ["Radio", "RadioGroup"],
  },
} as { [category: string]: { [unit: string]: string[] } };
