import { Icons } from "@aristobyte-ui/utils";

export const Config = {
  introLinks: (unit: string) => [
    {
      id: "storybook",
      // @TODO: insert proper href
      href: `https://storybook/${unit}`,
      target: "_blank",
      Icon: Icons.Storybook,
    },
    {
      id: "npm",
      href: `http://npmjs.com/package/@aristobyte-ui/${unit}`,
      target: "_blank",
      Icon: Icons.Npm,
    },
    {
      id: "source",
      href: `https://github.com/aristobyte-team/aristobyte-ui/tree/master/packages/${unit}`,
      target: "_blank",
      Icon: Icons.Github,
    },
  ],
  sidebar: {
    sections: [
      {
        id: "get-started",
        links: [
          {
            id: "introduction",
            href: "/get-started/introduction",
            target: "_self",
          },
          {
            id: "installation",
            href: "/get-started/installation",
            target: "_self",
          },
        ],
      },
      {
        id: "presets",
        links: [
          {
            id: "social-media-card",
            href: "/presets/social-media-card",
            taget: "_self",
          },
          {
            id: "music-player",
            href: "/presets/music-player",
            taget: "_self",
          },
          {
            id: "statistics-cards",
            href: "/presets/statistics-cards",
            taget: "_self",
          },
          {
            id: "settings-panel",
            href: "/presets/settings-panel",
            taget: "_self",
          },
          {
            id: "action-buttons",
            href: "/presets/action-buttons",
            taget: "_self",
          },
          {
            id: "status-indicators",
            href: "/presets/status-indicators",
            taget: "_self",
          },
          {
            id: "navigation-pills",
            href: "/presets/navigation-pills",
            taget: "_self",
          },
          {
            id: "quick-actions",
            href: "/presets/quick-actions",
            taget: "_self",
          },
          {
            id: "weather-widget",
            href: "/presets/weather-widget",
            taget: "_self",
          },
          {
            id: "notification-cards",
            href: "/presets/notification-cards",
            taget: "_self",
          },
          {
            id: "todo-list",
            href: "/presets/todo-list",
            taget: "_self",
          },
          {
            id: "chat-messages",
            href: "/presets/chat-messages",
            taget: "_self",
          },
          {
            id: "activity-feed",
            href: "/presets/activity-feed",
            taget: "_self",
          },
          {
            id: "shopping-cart",
            href: "/presets/shopping-cart",
            taget: "_self",
          },
          {
            id: "file-upload-area",
            href: "/presets/file-upload-area",
            taget: "_self",
          },
          {
            id: "progress-tracker",
            href: "/presets/progress-tracker",
            taget: "_self",
          },
          {
            id: "media-controls",
            href: "/presets/media-controls",
            taget: "_self",
          },
          {
            id: "pricing-card",
            href: "/presets/pricing-card",
            taget: "_self",
          },
          {
            id: "calendar-widget",
            href: "/presets/calendar-widget",
            taget: "_self",
          },
          {
            id: "device-status",
            href: "/presets/device-status",
            taget: "_self",
          },
          {
            id: "analytics-dashboard",
            href: "/presets/analytics-dashboard",
            taget: "_self",
          },
          {
            id: "contact-card",
            href: "/presets/contact-card",
            taget: "_self",
          },
          {
            id: "file-manager",
            href: "/presets/file-manager",
            taget: "_self",
          },
          {
            id: "quick-stats",
            href: "/presets/quick-stats",
            taget: "_self",
          },
          {
            id: "mini-menu",
            href: "/presets/mini-menu",
            taget: "_self",
          },
          {
            id: "notification-badges",
            href: "/presets/notification-badges",
            taget: "_self",
          },
          {
            id: "profile-badge",
            href: "/presets/profile-badge",
            taget: "_self",
          },
          {
            id: "time-&-location-widget",
            href: "/presets/time-&-location-widget",
            taget: "_self",
          },
          {
            id: "energy-meter",
            href: "/presets/energy-meter",
            taget: "_self",
          },
          {
            id: "cryptocurrency-widget",
            href: "/presets/cryptocurrency-widget",
            taget: "_self",
          },
          {
            id: "gaming-controller-widget",
            href: "/presets/gaming-controller-widget",
            taget: "_self",
          },
          {
            id: "streak-counter",
            href: "/presets/streak-counter",
            taget: "_self",
          },
          {
            id: "layer-stack-widget",
            href: "/presets/layer-stack-widget",
            taget: "_self",
          },
          {
            id: "inspiration-widget",
            href: "/presets/inspiration-widget",
            taget: "_self",
          },
          {
            id: "nature-widget",
            href: "/presets/nature-widget",
            taget: "_self",
          },
          {
            id: "reading-progress",
            href: "/presets/reading-progress",
            taget: "_self",
          },
          {
            id: "idea-bulb-widget",
            href: "/presets/idea-bulb-widget",
            taget: "_self",
          },
          {
            id: "rocket-launch-widget",
            href: "/presets/rocket-launch-widget",
            taget: "_self",
          },
          {
            id: "tool-widget",
            href: "/presets/tool-widget",
            taget: "_self",
          },
          {
            id: "color-palette-widget",
            href: "/presets/color-palette-widget",
            taget: "_self",
          },
          {
            id: "system-status",
            href: "/presets/system-status",
            taget: "_self",
          },
          {
            id: "pomodoro-timer",
            href: "/presets/pomodoro-timer",
            taget: "_self",
          },
          {
            id: "database-widget",
            href: "/presets/database-widget",
            taget: "_self",
          },
          {
            id: "network-status",
            href: "/presets/network-status",
            taget: "_self",
          },
          {
            id: "code-stats",
            href: "/presets/code-stats",
            taget: "_self",
          },
          {
            id: "mouse-tracker",
            href: "/presets/mouse-tracker",
            taget: "_self",
          },
          {
            id: "design-system",
            href: "/presets/design-system",
            taget: "_self",
          },
          {
            id: "ai-assistant",
            href: "/presets/ai-assistant",
            taget: "_self",
          },
          {
            id: "office-building-widget",
            href: "/presets/office-building-widget",
            taget: "_self",
          },
          {
            id: "team-collaboration-widget",
            href: "/presets/team-collaboration-widget",
            taget: "_self",
          },
          {
            id: "health-monitor",
            href: "/presets/health-monitor",
            taget: "_self",
          },
          {
            id: "email-dashboard",
            href: "/presets/email-dashboard",
            taget: "_self",
          },
          {
            id: "document-scanner",
            href: "/presets/document-scanner",
            taget: "_self",
          },
          {
            id: "social-engagement",
            href: "/presets/social-engagement",
            taget: "_self",
          },
          {
            id: "video-call-widget",
            href: "/presets/video-call-widget",
            taget: "_self",
          },
          {
            id: "task-manager",
            href: "/presets/task-manager",
            taget: "_self",
          },
          {
            id: "fitness-tracker",
            href: "/presets/fitness-tracker",
            taget: "_self",
          },
          {
            id: "cloud-storage",
            href: "/presets/cloud-storage",
            taget: "_self",
          },
          {
            id: "language-learning",
            href: "/presets/language-learning",
            taget: "_self",
          },
          {
            id: "stock-market",
            href: "/presets/stock-market",
            taget: "_self",
          },
          {
            id: "recipe-finder",
            href: "/presets/recipe-finder",
            taget: "_self",
          },
          {
            id: "travel-planner",
            href: "/presets/travel-planner",
            taget: "_self",
          },
          {
            id: "budget-tracker",
            href: "/presets/budget-tracker",
            taget: "_self",
          },
          {
            id: "password-manager",
            href: "/presets/password-manager",
            taget: "_self",
          },
          {
            id: "photo-editor",
            href: "/presets/photo-editor",
            taget: "_self",
          },
          {
            id: "music-production",
            href: "/presets/music-production",
            taget: "_self",
          },
          {
            id: "shopping-list",
            href: "/presets/shopping-list",
            taget: "_self",
          },
          {
            id: "habit-tracker",
            href: "/presets/habit-tracker",
            taget: "_self",
          },
          {
            id: "code-editor",
            href: "/presets/code-editor",
            taget: "_self",
          },
        ],
      },
      {
        id: "components",
        links: [
          {
            id: "button",
            href: "/components/button",
            target: "_self",
          },
          {
            id: "card",
            href: "/components/card",
            target: "_self",
          },
          {
            id: "dropdown",
            href: "/components/dropdown",
            target: "_self",
          },
          {
            id: "message-box",
            href: "/components/message-box",
            target: "_self",
          },
          {
            id: "radio",
            href: "/components/radio",
            target: "_self",
          },
          {
            id: "spinner",
            href: "/components/spinner",
            target: "_self",
          },
          {
            id: "switch",
            href: "/components/switch",
            target: "_self",
          },
        ],
      },
    ],
  },
  installation: [
    {
      id: "npm",
      label: "npm",
      script: "npm install",
      Icon: Icons.Npm,
    },
    {
      id: "yarn",
      label: "yarn",
      script: "yarn add",
      Icon: Icons.Yarn,
    },
    {
      id: "pnpm",
      label: "pnpm",
      script: "pnpm add",
      Icon: Icons.Pnpm,
    },
    {
      id: "bun",
      label: "bun",
      script: "bun add",
      Icon: Icons.Bun,
    },
  ],
  codePreviewTabs: ["preview", "code"],
  importTabs: ["individual", "global"],
  import: {
    presets: {
      "social-media-card": ["SocialMediaCard"],
      "music-player": ["MusicPlayer"],
      "statistics-cards": ["StatisticsCards"],
      "settings-panel": ["SettingsPanel"],
      "action-buttons": ["ActionButtons"],
      "status-indicators": ["StatusIndicators"],
      "navigation-pills": ["NavigationPills"],
      "quick-actions": ["QuickActions"],
      "weather-widget": ["WeatherWidget"],
      "notification-cards": ["NotificationCards"],
      "todo-list": ["TodoList"],
      "chat-messages": ["ChatMessages"],
      "activity-feed": ["ActivityFeed"],
      "shopping-cart": ["ShoppingCart"],
      "file-upload-area": ["FileUploadArea"],
      "progress-tracker": ["ProgressTracker"],
      "media-controls": ["MediaControls"],
      "pricing-card": ["PricingCard"],
      "calendar-widget": ["CalendarWidget"],
      "device-status": ["DeviceStatus"],
      "analytics-dashboard": ["AnalyticsDashboard"],
      "contact-card": ["ContactCard"],
      "file-manager": ["FileManager"],
      "quick-stats": ["QuickStats"],
      "mini-menu": ["MiniMenu"],
      "notification-badges": ["NotificationBadges"],
      "profile-badge": ["ProfileBadge"],
      "time-&-location-widget": ["Time&LocationWidget"],
      "energy-meter": ["EnergyMeter"],
      "cryptocurrency-widget": ["CryptocurrencyWidget"],
      "gaming-controller-widget": ["GamingControllerWidget"],
      "streak-counter": ["StreakCounter"],
      "layer-stack-widget": ["LayerStackWidget"],
      "inspiration-widget": ["InspirationWidget"],
      "nature-widget": ["NatureWidget"],
      "reading-progress": ["ReadingProgress"],
      "idea-bulb-widget": ["IdeaBulbWidget"],
      "rocket-launch-widget": ["RocketLaunchWidget"],
      "tool-widget": ["ToolWidget"],
      "color-palette-widget": ["ColorPaletteWidget"],
      "system-status": ["SystemStatus"],
      "pomodoro-timer": ["PomodoroTimer"],
      "database-widget": ["DatabaseWidget"],
      "network-status": ["NetworkStatus"],
      "code-stats": ["CodeStats"],
      "mouse-tracker": ["MouseTracker"],
      "design-system": ["DesignSystem"],
      "ai-assistant": ["AIAssistant"],
      "office-building-widget": ["OfficeBuildingWidget"],
      "team-collaboration-widget": ["TeamCollaborationWidget"],
      "health-monitor": ["HealthMonitor"],
      "email-dashboard": ["EmailDashboard"],
      "document-scanner": ["DocumentScanner"],
      "social-engagement": ["SocialEngagement"],
      "video-call-widget": ["VideoCallWidget"],
      "task-manager": ["TaskManager"],
      "fitness-tracker": ["FitnessTracker"],
      "cloud-storage": ["CloudStorage"],
      "language-learning": ["LanguageLearning"],
      "stock-market": ["StockMarket"],
      "recipe-finder": ["RecipeFinder"],
      "travel-planner": ["TravelPlanner"],
      "budget-tracker": ["BudgetTracker"],
      "password-manager": ["PasswordManager"],
      "photo-editor": ["PhotoEditor"],
      "music-production": ["MusicProduction"],
      "shopping-list": ["ShoppingList"],
      "habit-tracker": ["HabitTracker"],
      "code-editor": ["CodeEditor"],
    },
    components: {
      button: ["Button", "ButtonGroup"],
      card: ["Card"],
      dropdown: ["Dropdown", "DropdownOption"],
      home: ["ComponentName"],
      "message-box": ["MessageBox"],
      spinner: ["Spinner"],
      switch: ["Switch"],
      radio: ["Radio", "RadioGroup"],
    },
  } as { [category: string]: { [unit: string]: string[] } },
};
export type ConfigType = typeof Config;
